name: CI

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Create '.env' file and add environment variables
        env:
            DESCOPE_PROJECT_ID: ${{ vars.DESCOPE_PROJECT_ID }}
            DESCOPE_FLOW_URL: ${{ vars.DESCOPE_FLOW_URL }}
        run: |
            echo "DESCOPE_PROJECT_ID=$(DESCOPE_PROJECT_ID)" > .env
            echo "DESCOPE_FLOW_URL=$(DESCOPE_FLOW_URL)" >> .env
  
      - name: Dependencies
        run: flutter pub get
      - name: Analyze
        run: dart analyze
      - name: Test
        run: flutter test